// Auto-generated by scripts/refresh-reports.mjs (GitHub Actions workflow
// .github/workflows/refresh-reports.yml, runs daily). Do not hand-edit — your
// changes will be overwritten on the next run. This is raw, unedited text
// scraped directly from each guide's own site — no AI summarizing involved.
const AUTO_REPORTS = [
  {
    "date": "2026-10-02",
    "source": "Patriot Guide Service (Justin Chromy)",
    "sourceUrl": "https://www.patriotguideserviceoflakevermilion.com/10-02-26-lake-vermilion-fishing-report/",
    "waterTempF": null,
    "rawText": "This is likely the last written fishing report of the season for me. If you follow me on YouTube, I’ll try to get one more video out yet. Thank you all for making the 2026 guide season the best one I’ve ever had! EAST END WALLEYES: The best luck we’ve had in the past week has been on the sides and bottoms of rocks in 12 to 20 feet of water. Minnows have overall started to outproduce crawlers on the Lindy Rigs and jigs, but there are still times and places where the worms work better. Moving often is important to find the right group of fish that are willing to bite. There are several other patterns that will work as well, per usual for late September, early October. With water temps in the low 60s, it won’t be long before fish stack up in the deep holes and are easy to catch. WEST END WALLEYES: Walleye fishing continues to be good for us on the west end. The best bite is on deeper rocks in 25 to 30 feet with a jig and a minnow. Catching a few fish on a spot and moving on from there is pretty normal. Most of these fish are of the 13 inch variety, with some larger ones and slot fish mixed in. Nicer sized walleyes are on the sand in front of weed-lines in 12 to 20 feet. While these fish are picky at times, we have gotten them to bite with a jig/minnow, jig/crawler, and Lindy Rigs with minnows or crawlers as well. This has been a good fall bite on Lake Vermilion, and I expect the bite to continue to improve as we go further into October! Unfortunately for me, life calls and I only have a couple of trips left. I would like to thank everyone for their support. You really helped make this guide season something special. I’m looking forward to another great summer in 2027."
  },
  {
    "date": "2026-09-23",
    "source": "Patriot Guide Service (Justin Chromy)",
    "sourceUrl": "https://www.patriotguideserviceoflakevermilion.com/09-23-26-lake-vermilion-fishing-report/",
    "waterTempF": null,
    "rawText": "Another fun week on Vermilion – good fishing and the fall colors are starting to pop! EAST END WALLEYES: The best bite continues to be in transition areas along the bottoms of rocks in 12 to 25 feet. This area is usually sand, but it can sometimes be mud. The best way to attack these fish is with a Lindy Rig and live bait. All three methods (crawlers, leeches, and minnows) are working now. Jigs will work in some instances as well, but we are seeing fish more spread out around the structures. There are fish in several other areas as well. As shallow as a couple feet of water and 30’+. Keep moving until fish are located and be prepared to fish multiple ways to have a good day on the water. WEST END WALLEYES: The bite on the west side is pretty similar to the east end with several different patterns taking place. Some fish are in the sand in 10 to 20 feet, some are on the deep edges of rocks in 12 to 30 feet, there are some Leadcore fish being caught in 20-30 feet, and some fish showing up around the deep holes as well in 30 feet of water. There is a time and place for every technique you can bust out, but the bite is good multiple different ways! We are approaching the peak of fall fishing! The fall walleye bite is only getting better. Justin has limited availability October 6-10, so don’t miss your chance to experience Lake Vermilion at its best. Call 218-820-0355 or reserve your fall fishing trip online."
  },
  {
    "date": "2026-08-31",
    "source": "Fishing with Z (Zach Hrvol)",
    "sourceUrl": "https://fishingwithz.com/week-16-august-24-31-2026/",
    "waterTempF": "69–72",
    "rawText": "Week #16: 8/24-8/31, 2026 Water temps: 69-72 Another inconsistent week of fishing but we managed to put quality fish in the boat! We didn’t catch…"
  }
];
