// Auto-generated by scripts/refresh-reports.mjs — always rewritten on every run
// (unlike reports.auto.js, which only changes when new report content is found).
// Use this to confirm the daily refresh actually ran, independent of whether
// either guide had posted anything new.
const REPORTS_CHECKED_AT = "2026-09-19T12:17:39.611Z";
const REPORTS_CHECK_STATUS = [
  {
    "source": "Fishing with Z",
    "ok": true
  },
  {
    "source": "Patriot Guide Service",
    "ok": true
  }
];
