// Auto-generated by scripts/refresh-reports.mjs (GitHub Actions workflow
// .github/workflows/refresh-reports.yml, runs daily). Do not hand-edit — your
// changes will be overwritten on the next run. This is raw, unedited text
// scraped directly from each guide's own site — no AI summarizing involved.
const AUTO_REPORTS = [
  {
    "date": "2026-08-31",
    "source": "Fishing with Z (Zach Hrvol)",
    "sourceUrl": "https://fishingwithz.com/week-16-august-24-31-2026/",
    "waterTempF": "69–72",
    "rawText": "Week #16: 8/24-8/31, 2026 Water temps: 69-72 Another inconsistent week of fishing but we managed to put quality fish in the boat! We didn’t catch…"
  },
  {
    "date": "2026-09-15",
    "source": "Patriot Guide Service (Justin Chromy)",
    "sourceUrl": "https://www.patriotguideserviceoflakevermilion.com/09-15-26-lake-vermilion-fishing-report/",
    "waterTempF": null,
    "rawText": "Steady fall fishing continues on Vermilion, with bigger fish continuing to show up! EAST END WALLEYES: Fishing has been good on transitional areas on the bottoms of rocks in 12 to 25 feet. A sand strip between the rocks and mud is where the fish have been sitting. Lindy rigging with a leech or a crawler has still been our best method. Expect minnows to pick up soon. Deeper depths will work for this pattern, but this is where we have been fishing. There are some Leadcore fish to be had as well. Trolling Number 5 Flicker Shads and Shad Raps at 2.0 to 2.5 mph in the 20 to 35 foot mud basins will yield the best results. WEST END WALLEYES: The best bite has been trolling Leadcore in 20 to 30 foot mud basins. Trolling at 2.5mph has been the best bet with Number 5 and Number 7 Flicker Shads and Shad Raps producing about equally. We have been using more Shad Raps than Flicker Shads, but that may be more personal preference than anything. Experience the beauty of fall on Lake Vermilion while targeting some of the biggest walleyes of the season. Justin still has a few openings October 6-10. Contact Patriot Guide Service today to book your adventure!"
  }
];
