#!/usr/bin/env node
// Pulls the latest fishing report from each guide's own site and rewrites
// reports.auto.js. No AI involved — this is plain extraction of text that's
// already public on each site, run daily by
// .github/workflows/refresh-reports.yml. If a site's page structure changes
// enough to break the regex below, this just leaves that source's entry as
// it was (logged as a warning) rather than writing garbage.

import { writeFile } from 'node:fs/promises';

function cleanText(s) {
  return s
    .replace(/&#8230;/g, '…')
    .replace(/&nbsp;/g, ' ')
    .replace(/&#039;/g, "'")
    .replace(/&amp;/g, '&')
    .replace(/<[^>]+>/g, '')
    .replace(/\s+/g, ' ')
    .trim();
}

function extractWaterTemp(text) {
  const m = text.match(/Water temps?:?\s*(\d{2}-\d{2})/i);
  return m ? m[1].replace('-', '–') : null;
}

async function fetchText(url) {
  const res = await fetch(url, { headers: { 'User-Agent': 'lake-vermilion-app-report-refresh/1.0' } });
  if (!res.ok) throw new Error(`${url} -> HTTP ${res.status}`);
  return res.text();
}

async function scrapeFishingWithZ() {
  const listUrl = 'https://fishingwithz.com/fishing-reports/';
  const html = await fetchText(listUrl);
  const m = html.match(/<h2><a href="([^"]+)"[^>]*>([^<]+)<\/a><\/h2>[\s\S]*?<p>Posted ([^<]+)<\/p>[\s\S]*?<p>([^<]+)<\/p>/);
  if (!m) { console.warn('Fishing with Z: pattern not found, skipping'); return null; }
  const [, link, , dateStr, excerpt] = m;
  const iso = new Date(dateStr.trim()).toISOString().slice(0, 10);
  const rawText = cleanText(excerpt);
  return {
    date: iso,
    source: 'Fishing with Z (Zach Hrvol)',
    sourceUrl: link,
    waterTempF: extractWaterTemp(rawText),
    rawText
  };
}

async function scrapePatriotGuide() {
  const listUrl = 'https://www.patriotguideserviceoflakevermilion.com/fishing-reports/';
  const html = await fetchText(listUrl);
  // This listing page mixes weekly reports with evergreen blog posts in the same
  // carousel widget, so filter to titles that actually look like a dated report
  // before picking the most recent one.
  const re = /itemid="([^"]+)" content="([^"]+)" \/><meta itemprop="datePublished" content="([^"]+)"/g;
  const all = [...html.matchAll(re)].map(m => ({ link: m[1], title: m[2], date: m[3] }));
  const reports = all.filter(a => /^\d{2}\/\d{2}\/\d{2} Lake Vermilion Fishing Report$/.test(a.title));
  if (reports.length === 0) { console.warn('Patriot Guide Service: no dated reports found, skipping'); return null; }
  reports.sort((a, b) => new Date(b.date) - new Date(a.date));
  const latest = reports[0];
  const titleMatch = latest.title.match(/^(\d{2})\/(\d{2})\/(\d{2})/);
  const reportDate = titleMatch ? `20${titleMatch[3]}-${titleMatch[1]}-${titleMatch[2]}` : latest.date.slice(0, 10);

  const postHtml = await fetchText(latest.link);
  const paraMatches = [...postHtml.matchAll(/<p class="wp-block-paragraph">([\s\S]*?)<\/p>/g)];
  if (paraMatches.length === 0) { console.warn('Patriot Guide Service: post body not found, skipping'); return null; }
  const rawText = cleanText(paraMatches.map(p => p[1]).join(' '));
  return {
    date: reportDate,
    source: 'Patriot Guide Service (Justin Chromy)',
    sourceUrl: latest.link,
    waterTempF: extractWaterTemp(rawText),
    rawText
  };
}

async function main() {
  const results = await Promise.allSettled([scrapeFishingWithZ(), scrapePatriotGuide()]);
  const reports = [];
  for (const r of results) {
    if (r.status === 'fulfilled' && r.value) reports.push(r.value);
    else if (r.status === 'rejected') console.warn('Scrape failed:', r.reason?.message || r.reason);
  }
  if (reports.length === 0) {
    console.error('No reports scraped successfully from either source — leaving reports.auto.js untouched.');
    process.exit(0); // not a failure of the workflow, just nothing to update
  }

  const body = `// Auto-generated by scripts/refresh-reports.mjs (GitHub Actions workflow\n` +
    `// .github/workflows/refresh-reports.yml, runs daily). Do not hand-edit — your\n` +
    `// changes will be overwritten on the next run. This is raw, unedited text\n` +
    `// scraped directly from each guide's own site — no AI summarizing involved.\n` +
    `const AUTO_REPORTS = ${JSON.stringify(reports, null, 2)};\n`;

  await writeFile(new URL('../reports.auto.js', import.meta.url), body, 'utf8');
  console.log(`Wrote reports.auto.js with ${reports.length} report(s).`);
}

main().catch(err => {
  console.error(err);
  process.exit(1);
});
